fix jq expression

diff --git a/.github/workflows/pr-github-checks.yml b/.github/workflows/pr-github-checks.yml
--- a/.github/workflows/pr-github-checks.yml
+++ b/.github/workflows/pr-github-checks.yml
@@ -22,7 +22,7 @@ jobs:
         if: always()
         run: |
           gh api --jq '.labels.[].name' /repos/${{ github.repository }}/pulls/${{ github.event.number }} | \
-          grep -q '^area/' || exit 1
+          grep -q '^area/' || (echo "area label missing"; exit 1)
         env:
           GH_TOKEN: ${{ github.token }}
 
@@ -30,7 +30,7 @@ jobs:
         if: always()
         run: |
           gh api --jq '.labels.[].name' /repos/${{ github.repository }}/pulls/${{ github.event.number }} | \
-          grep -q '^kind/' || exit 1
+          grep -q '^kind/' || (echo "kind label missing"; exit 1)
         env:
           GH_TOKEN: ${{ github.token }}
 
@@ -39,7 +39,7 @@ jobs:
         run: |
           kind_label=$( gh api --jq '.labels.[].name' /repos/${{ github.repository }}/pulls/${{ github.event.number }} | grep '^kind/')
           kind_label_to_pr_title_prefix='{"kind/bug":"fix","kind/feature":"feat","kind/docs":"docs","kind/chore":"chore","kind/test":"test","kind/deps":"deps"}'
-          prefix=$(echo $kind_label_to_pr_title_prefix | jq -r ".$kind_label")
+          prefix=$(echo $kind_label_to_pr_title_prefix | jq -r ".\"$kind_label\"")
           if [[ ! ${{ github.event.pull_request.title }} =~ ^$prefix ]]; then
             echo "PR title should start with $prefix"
             exit 1
